#!/usr/bin/env bash

set -e
set -o pipefail

declare -a files_to_put=(
    ./lazypdf
    ./multiple
)

INSTALL_DIR="${HOME}/.local/bin/"

mark_executable() {
    chmod 744 "$1" || (
        printf "error: chmod 744 $1\n"
        exit 1
    )
}

put() {
    cp "$1" "${INSTALL_DIR}" || (
        printf "error: cp $1 ${INSTALL_DIR}\n"
        exit 1
    )
}

if [[ :$PATH: != *:"${INSTALL_DIR}":* ]]; then
    printf "error: ${INSTALL_DIR} is not in \$PATH; update your \$PATH variable\n"
    exit 1
fi

for file in "${files_to_put[@]}"; do
    printf "Put ${file} in ${INSTALL_DIR}\n"
    put "${file}"
    mark_executable "${INSTALL_DIR}/${file}"
done
